version: '2'

services:
  couchbase:
    image: couchbase-custom
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
    environment:
      - COUCHBASE_ADMINISTRATOR_USERNAME=Administrator
      - COUCHBASE_ADMINISTRATOR_PASSWORD=password
      - COUCHBASE_BUCKET=default
      - COUCHBASE_BUCKET_PASSWORD=

  spring-boot:
    image: spring-boot-custom
    ports:
      - 8080:8080
    environment:
      - COUCHBASE_HOST_NAME=couchbase
      - COUCHBASE_BUCKET=default
      - COUCHBASE_PASSWORD=password
      - COUCHBASE_USERNAME=Administrator
    restart: always