version: '2'

services:
  couchbase:
    image: couchbase-custom
    networks:
      - persistentStore
    ports:
      - "8091:8091"
    environment:
      - COUCHBASE_ADMINISTRATOR_USERNAME=Administrator
      - COUCHBASE_ADMINISTRATOR_PASSWORD=password
      - COUCHBASE_BUCKET=default
      - COUCHBASE_BUCKET_PASSWORD=

  spring-boot:
    image: spring-boot-custom
    networks:
      - persistentStore
    ports:
      - 8080:8080
    environment:
      - COUCHBASE_HOSTNAME=couchbase
      - COUCHBASE_BUCKET=default
      - COUCHBASE_PASSWORD=password
      - COUCHBASE_USERNAME=Administrator
    restart: always
networks:
  persistentStore: